-- ============================================
-- PostgreSQL schema para Sistema de Producción de Moldes
-- ============================================

-- Nota: asume schema 'public'.

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- Usuarios y Operarios
-- ============================================

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('admin', 'planner', 'operator')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_username ON users (username);

CREATE TABLE IF NOT EXISTS operators (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  user_id INTEGER NULL REFERENCES users(id) ON DELETE CASCADE,
  password_hash VARCHAR(255) NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uniq_operator_name UNIQUE (name)
);
CREATE INDEX IF NOT EXISTS idx_user_id ON operators (user_id);

-- ============================================
-- Catálogos principales
-- ============================================

CREATE TABLE IF NOT EXISTS processes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS machines (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  daily_capacity NUMERIC(5,2) NULL,
  notes TEXT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_name ON machines (name);

CREATE TABLE IF NOT EXISTS molds (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS mold_parts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  reason TEXT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS operations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================
-- Planificador y calendario
-- ============================================

CREATE TABLE IF NOT EXISTS plan_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mold_id INTEGER NOT NULL REFERENCES molds(id) ON DELETE CASCADE,
  part_id INTEGER NOT NULL REFERENCES mold_parts(id) ON DELETE CASCADE,
  machine_id INTEGER NOT NULL REFERENCES machines(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  hours_planned NUMERIC(5,2) NOT NULL,
  is_priority BOOLEAN NOT NULL DEFAULT FALSE,
  created_by INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_plan_entries_date_machine ON plan_entries (date, machine_id);
CREATE INDEX IF NOT EXISTS idx_plan_entries_mold_part_machine ON plan_entries (mold_id, part_id, machine_id);

CREATE TABLE IF NOT EXISTS holidays (
  date DATE PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS working_overrides (
  date DATE PRIMARY KEY,
  is_working BOOLEAN NOT NULL DEFAULT TRUE
);

-- ============================================
-- Snapshots de parrilla del Planificador (para reabrir exactamente lo digitado)
-- ============================================

CREATE TABLE IF NOT EXISTS planner_grid_snapshots (
  mold_id INTEGER NOT NULL REFERENCES molds(id) ON DELETE CASCADE,
  start_date DATE NOT NULL,
  snapshot_json JSONB NOT NULL,
  created_by INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
  updated_by INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (mold_id, start_date)
);

CREATE INDEX IF NOT EXISTS idx_planner_grid_snapshots_updated_at ON planner_grid_snapshots (updated_at);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'trg_planner_grid_snapshots_set_updated_at'
  ) THEN
    CREATE TRIGGER trg_planner_grid_snapshots_set_updated_at
    BEFORE UPDATE ON planner_grid_snapshots
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

-- ============================================
-- Tiempos trabajados (Work logs)
-- ============================================

CREATE TABLE IF NOT EXISTS work_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mold_id INTEGER NOT NULL REFERENCES molds(id) ON DELETE CASCADE,
  part_id INTEGER NOT NULL REFERENCES mold_parts(id) ON DELETE CASCADE,
  machine_id INTEGER NOT NULL REFERENCES machines(id) ON DELETE CASCADE,
  operator_id INTEGER NOT NULL REFERENCES operators(id) ON DELETE RESTRICT,
  work_date DATE NULL,
  hours_worked NUMERIC(5,2) NOT NULL,
  planned_hours_snapshot NUMERIC(5,2) NULL,
  reason TEXT NULL,
  note TEXT NULL,
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_work_logs_recorded_at ON work_logs (recorded_at);
CREATE INDEX IF NOT EXISTS idx_work_logs_work_date ON work_logs (work_date);
CREATE INDEX IF NOT EXISTS idx_work_logs_operator_date ON work_logs (operator_id, work_date);
CREATE INDEX IF NOT EXISTS idx_work_logs_machine_date ON work_logs (machine_id, recorded_at);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'trg_work_logs_set_updated_at'
  ) THEN
    CREATE TRIGGER trg_work_logs_set_updated_at
    BEFORE UPDATE ON work_logs
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

-- ============================================
-- Auditoría de sesiones (login/logout)
-- ============================================

CREATE TABLE IF NOT EXISTS user_sessions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  operator_id INTEGER NULL REFERENCES operators(id) ON DELETE SET NULL,
  role TEXT NOT NULL CHECK (role IN ('admin', 'planner', 'operator')),
  ip VARCHAR(64) NULL,
  user_agent VARCHAR(255) NULL,
  login_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  logout_at TIMESTAMPTZ NULL
);
CREATE INDEX IF NOT EXISTS idx_user_sessions_user ON user_sessions (user_id);
CREATE INDEX IF NOT EXISTS idx_user_sessions_login ON user_sessions (login_at);

-- ============================================
-- Indicadores (mensual)
-- ============================================

CREATE TABLE IF NOT EXISTS operator_working_days_monthly (
  operator_id INTEGER NOT NULL REFERENCES operators(id) ON DELETE CASCADE,
  year SMALLINT NOT NULL,
  month SMALLINT NOT NULL CHECK (month BETWEEN 1 AND 12),
  working_days INTEGER NOT NULL,
  updated_by INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (operator_id, year, month)
);
CREATE INDEX IF NOT EXISTS idx_op_days_year_month ON operator_working_days_monthly (year, month);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'trg_op_days_set_updated_at'
  ) THEN
    CREATE TRIGGER trg_op_days_set_updated_at
    BEFORE UPDATE ON operator_working_days_monthly
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

-- ============================================
-- Importación
-- ============================================

CREATE TABLE IF NOT EXISTS import_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_name VARCHAR(255) NOT NULL,
  total_rows INTEGER NOT NULL DEFAULT 0,
  success_count INTEGER NOT NULL DEFAULT 0,
  fail_count INTEGER NOT NULL DEFAULT 0,
  created_by INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_import_batches_created_at ON import_batches (created_at);

CREATE TABLE IF NOT EXISTS import_errors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id BIGINT NOT NULL REFERENCES import_batches(id) ON DELETE CASCADE,
  row_no INTEGER NOT NULL,
  nombre_operario VARCHAR(255) NULL,
  tipo_proceso VARCHAR(255) NULL,
  molde VARCHAR(255) NULL,
  parte VARCHAR(255) NULL,
  maquina VARCHAR(255) NULL,
  operacion VARCHAR(255) NULL,
  horas_original VARCHAR(255) NULL,
  reason VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_import_errors_batch_row ON import_errors (batch_id, row_no);

-- ============================================
-- Datos (histórico)
-- ============================================

CREATE TABLE IF NOT EXISTS datos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dia SMALLINT NULL,
  mes VARCHAR(20) NULL,
  anio SMALLINT NULL,

  nombre_operario VARCHAR(100) NULL,
  tipo_proceso VARCHAR(100) NULL,
  molde VARCHAR(150) NULL,
  parte VARCHAR(150) NULL,
  maquina VARCHAR(100) NULL,
  operacion VARCHAR(150) NULL,

  operator_id INTEGER NULL REFERENCES operators(id) ON DELETE SET NULL,
  process_id INTEGER NULL REFERENCES processes(id) ON DELETE SET NULL,
  mold_id INTEGER NULL REFERENCES molds(id) ON DELETE SET NULL,
  part_id INTEGER NULL REFERENCES mold_parts(id) ON DELETE SET NULL,
  machine_id INTEGER NULL REFERENCES machines(id) ON DELETE SET NULL,
  operation_id INTEGER NULL REFERENCES operations(id) ON DELETE SET NULL,

  horas NUMERIC(6,2) NULL,
  source TEXT NOT NULL DEFAULT 'manual' CHECK (source IN ('manual','import')),
  import_batch_id BIGINT NULL REFERENCES import_batches(id) ON DELETE SET NULL,
  created_by INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_datos_dia_mes_anio ON datos (anio, mes, dia);
CREATE INDEX IF NOT EXISTS idx_datos_operario ON datos (nombre_operario);
CREATE INDEX IF NOT EXISTS idx_datos_molde_parte ON datos (molde, parte);
CREATE INDEX IF NOT EXISTS idx_datos_maquina ON datos (maquina);
CREATE INDEX IF NOT EXISTS idx_datos_source ON datos (source);
CREATE INDEX IF NOT EXISTS idx_datos_created_at ON datos (created_at);
CREATE INDEX IF NOT EXISTS idx_datos_operator_id ON datos (operator_id);
CREATE INDEX IF NOT EXISTS idx_datos_process_id ON datos (process_id);
CREATE INDEX IF NOT EXISTS idx_datos_mold_part_id ON datos (mold_id, part_id);
CREATE INDEX IF NOT EXISTS idx_datos_machine_id ON datos (machine_id);
CREATE INDEX IF NOT EXISTS idx_datos_operation_id ON datos (operation_id);

-- ============================================
-- Recetas por molde
-- ============================================

CREATE TABLE IF NOT EXISTS mold_recipes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mold_id INTEGER NOT NULL REFERENCES molds(id) ON DELETE CASCADE,
  created_by INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_mold_recipes_mold ON mold_recipes (mold_id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'trg_mold_recipes_set_updated_at'
  ) THEN
    CREATE TRIGGER trg_mold_recipes_set_updated_at
    BEFORE UPDATE ON mold_recipes
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS mold_recipe_lines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id BIGINT NOT NULL REFERENCES mold_recipes(id) ON DELETE CASCADE,
  part_id INTEGER NULL REFERENCES mold_parts(id) ON DELETE SET NULL,
  part_name VARCHAR(255) NULL,
  machine_id INTEGER NULL REFERENCES machines(id) ON DELETE SET NULL,
  machine_name VARCHAR(255) NULL,
  base_hours NUMERIC(6,2) NULL,
  sequence INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_recipe_seq ON mold_recipe_lines (recipe_id, sequence);

-- ============================================
-- Semillas (idempotentes)
-- ============================================

INSERT INTO machines (name, daily_capacity, is_active)
VALUES
  ('CNC VF3 #1', 15.00, TRUE),
  ('CNC VF3 #2', 15.00, TRUE),
  ('Fresadora #1', 14.00, TRUE),
  ('Fresadora #2', 14.00, TRUE),
  ('Torno CNC', 9.50, TRUE),
  ('Erosionadora', 14.00, TRUE),
  ('Rectificadora', 14.00, TRUE),
  ('Torno', 14.00, TRUE),
  ('Taladro radial', 14.00, TRUE),
  ('Pulida', 9.50, TRUE)
ON CONFLICT (name) DO UPDATE SET
  daily_capacity = EXCLUDED.daily_capacity,
  is_active = EXCLUDED.is_active;

INSERT INTO mold_parts (name, is_active)
VALUES
  ('Anillo de Expulsion', TRUE),
  ('Anillo de Registro', TRUE),
  ('Boquilla Principal', TRUE),
  ('Botador inclinado', TRUE),
  ('Buje de Expulsion', TRUE),
  ('Buje Principal', TRUE),
  ('Bujes de Rama', TRUE),
  ('Correderas', TRUE),
  ('Deflector de Refrigeración', TRUE),
  ('Devolvedores', TRUE),
  ('Electrodos', TRUE),
  ('Flanche actuador hidraulico', TRUE),
  ('Guia actuadur hidraulico', TRUE),
  ('Guia Principal', TRUE),
  ('Guias de expulsion', TRUE),
  ('Guias de Rama', TRUE),
  ('Haladores', TRUE),
  ('Hembra', TRUE),
  ('Hembra empotrada', TRUE),
  ('Limitadores de Placa Flotante', TRUE),
  ('Macho', TRUE),
  ('Macho Central', TRUE),
  ('Macho empotrado', TRUE),
  ('Molde completo', TRUE),
  ('Nylon', TRUE),
  ('Paralelas Porta Macho', TRUE),
  ('Pilares Soporte', TRUE),
  ('Placa anillos expulsores', TRUE),
  ('Placa de Expulsion', TRUE),
  ('Placa Expulsion de Rama', TRUE),
  ('Placa Portahembras', TRUE),
  ('Placa Portamachos', TRUE),
  ('placa respaldo anillos expulsores', TRUE),
  ('Placa Respaldo de Expulsion', TRUE),
  ('Placa Respaldo Hembras', TRUE),
  ('Placa Respaldo Inferior', TRUE),
  ('Placa Respaldo Machos', TRUE),
  ('Placa respaldo portamachos', TRUE),
  ('Placa Respaldo Superior', TRUE),
  ('Placa Tope', TRUE),
  ('Porta Fondo', TRUE),
  ('Retenedores de Rama', TRUE),
  ('Soporte correderas', TRUE),
  ('Soporte nylon', TRUE),
  ('Tapones de Enfriamiento', TRUE),
  ('Techos', TRUE)
ON CONFLICT (name) DO UPDATE SET
  is_active = EXCLUDED.is_active;